<april:sidebar-layout class="min-h-[620px] overflow-hidden rounded-xl border">
    <april:sidebar>
        <slot:header><div class="flex items-center gap-2 px-2"><div class="flex h-7 w-7 items-center justify-center rounded-md bg-primary text-primary-foreground"><x-lucide-layers-3 class="h-4 w-4" /></div><span class="font-semibold">Acme Inc.</span></div></slot:header>
        <slot:content>
            <april:sidebar-group><april:sidebar-group-label>Platform</april:sidebar-group-label><april:sidebar-group-content><april:sidebar-menu>@foreach ([['layout-dashboard', 'Overview'], ['inbox', 'Inbox'], ['calendar', 'Calendar']] as [$icon, $label])<april:sidebar-menu-item><april:sidebar-menu-button-link href="#" :active="$label === 'Overview'"><x-dynamic-component component="lucide-{{$icon}}" /><span>{{$label}}</span>@if ($label === 'Inbox')<april:sidebar-menu-badge>12</april:sidebar-menu-badge>@endif</april:sidebar-menu-button-link></april:sidebar-menu-item>@endforeach</april:sidebar-menu></april:sidebar-group-content></april:sidebar-group>
            <april:sidebar-group><april:sidebar-group-label>Manage</april:sidebar-group-label><april:sidebar-group-content><april:sidebar-menu>@foreach ([['users', 'Team'], ['settings', 'Settings']] as [$icon, $label])<april:sidebar-menu-item><april:sidebar-menu-button-link href="#"><x-dynamic-component component="lucide-{{$icon}}" /><span>{{$label}}</span></april:sidebar-menu-button-link></april:sidebar-menu-item>@endforeach</april:sidebar-menu></april:sidebar-group-content></april:sidebar-group>
        </slot:content>
        <slot:footer><div class="flex items-center gap-2 px-2"><april:avatar><slot:fallback>SC</slot:fallback></april:avatar><div class="min-w-0 flex-1 text-sm"><p class="truncate font-medium">Sofia Carter</p><p class="truncate text-xs text-muted-foreground">Pro plan</p></div><april:button type="button" variant="ghost" size="icon"><x-lucide-settings class="h-4 w-4" /></april:button></div></slot:footer>
    </april:sidebar>
    <april:sidebar-inset class="bg-muted/20"><header class="flex h-14 items-center gap-2 border-b bg-background px-4"><april:sidebar-trigger /><span class="text-sm font-medium">Overview</span></header><div class="p-6"><april:card><slot:title>Welcome back</slot:title><slot:content><p class="text-sm text-muted-foreground">Select a section from the sidebar to continue.</p></slot:content></april:card></div></april:sidebar-inset>
</april:sidebar-layout>
