<?php

return [
    'latest-version' => '0.x',

    'versions' => [
        '0.x' => [
            'label' => '0.x',
            'links' => [
                ['type' => 'header', 'text' => 'Getting Started'],
                ['href' => '/', 'text' => 'introduction'],
                ['href' => 'installation', 'text' => 'installation'],
                ['href' => '/examples', 'text' => 'examples', 'scope' => 'global'],
                ['href' => '/customize', 'text' => 'customize', 'scope' => 'global'],
                ['href' => 'theming', 'text' => 'theming'],
                ['href' => 'data-attributes', 'text' => 'data attributes'],
                ['type' => 'header', 'text' => 'Components'],
                ['href' => 'components/accordion', 'text' => 'Accordion'],
                ['href' => 'components/alert', 'text' => 'Alert'],
                ['href' => 'components/alert-dialog', 'text' => 'Alert Dialog'],
                ['href' => 'components/aspect-ratio', 'text' => 'Aspect Ratio'],
                ['href' => 'components/attachment', 'text' => 'Attachment'],
                ['href' => 'components/avatar', 'text' => 'Avatar'],
                ['href' => 'components/badge', 'text' => 'Badge'],
                ['href' => 'components/breadcrumb', 'text' => 'Breadcrumb'],
                ['href' => 'components/bubble', 'text' => 'Bubble'],
                ['href' => 'components/button', 'text' => 'Button'],
                ['href' => 'components/button-group', 'text' => 'Button Group'],
                ['href' => 'components/calendar', 'text' => 'Calendar'],
                ['href' => 'components/card', 'text' => 'Card'],
                ['href' => 'components/carousel', 'text' => 'Carousel'],
                ['href' => 'components/chart', 'text' => 'Chart'],
                ['href' => 'components/command', 'text' => 'Command'],
                ['href' => 'components/collapsible', 'text' => 'Collapsible'],
                ['href' => 'components/combobox', 'text' => 'Combobox'],
                ['href' => 'components/context-menu', 'text' => 'Context Menu'],
                ['href' => 'components/data-table', 'text' => 'Data Table'],
                ['href' => 'components/date-picker', 'text' => 'Date Picker'],
                ['href' => 'components/dialog', 'text' => 'Dialog'],
                ['href' => 'components/dropdown-menu', 'text' => 'Dropdown Menu'],
                ['href' => 'components/input', 'text' => 'Input'],
                ['href' => 'components/label', 'text' => 'Label'],
                ['href' => 'components/popover', 'text' => 'Popover'],
                ['href' => 'components/select', 'text' => 'Select'],
                ['href' => 'components/sheet', 'text' => 'Sheet'],
                ['href' => 'components/sidebar', 'text' => 'Sidebar'],
                ['href' => 'components/skeleton', 'text' => 'Skeleton'],
                ['href' => 'components/steps', 'text' => 'Steps'],
                ['href' => 'components/switch', 'text' => 'Switch'],
                ['href' => 'components/tabs', 'text' => 'Tabs'],
                ['href' => 'components/textarea', 'text' => 'Textarea'],
                ['href' => 'components/tooltip', 'text' => 'Tooltip'],
                ['type' => 'header', 'text' => 'Patterns'],
                ['href' => '/blocks', 'text' => 'Blocks', 'scope' => 'global'],
            ],
        ],
    ],
];
